# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(931, 698)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon-diaglog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.twListAcc = QtWidgets.QTreeWidget(Dialog)
        self.twListAcc.setEnabled(True)
        self.twListAcc.setGeometry(QtCore.QRect(20, 80, 891, 471))
        self.twListAcc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.twListAcc.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.twListAcc.setLineWidth(1)
        self.twListAcc.setAutoScroll(True)
        self.twListAcc.setColumnCount(8)
        self.twListAcc.setObjectName("twListAcc")
        self.pbImport = QtWidgets.QPushButton(Dialog)
        self.pbImport.setGeometry(QtCore.QRect(400, 50, 101, 23))
        self.pbImport.setObjectName("pbImport")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(580, 580, 81, 16))
        self.label.setObjectName("label")
        self.txtContents = QtWidgets.QTextEdit(Dialog)
        self.txtContents.setGeometry(QtCore.QRect(580, 600, 221, 81))
        self.txtContents.setObjectName("txtContents")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(580, 560, 47, 13))
        self.label_2.setObjectName("label_2")
        self.pbSend = QtWidgets.QPushButton(Dialog)
        self.pbSend.setGeometry(QtCore.QRect(820, 640, 75, 41))
        self.pbSend.setObjectName("pbSend")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 71, 20))
        self.label_3.setObjectName("label_3")
        self.spinDelay = QtWidgets.QSpinBox(Dialog)
        self.spinDelay.setGeometry(QtCore.QRect(220, 10, 51, 20))
        self.spinDelay.setMaximum(5)
        self.spinDelay.setProperty("value", 5)
        self.spinDelay.setObjectName("spinDelay")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(180, 10, 41, 16))
        self.label_4.setObjectName("label_4")
        self.lePath = QtWidgets.QLineEdit(Dialog)
        self.lePath.setGeometry(QtCore.QRect(20, 50, 321, 20))
        self.lePath.setObjectName("lePath")
        self.pbSelectFile = QtWidgets.QPushButton(Dialog)
        self.pbSelectFile.setGeometry(QtCore.QRect(360, 50, 31, 23))
        self.pbSelectFile.setObjectName("pbSelectFile")
        self.spinThread = QtWidgets.QSpinBox(Dialog)
        self.spinThread.setGeometry(QtCore.QRect(100, 10, 51, 20))
        self.spinThread.setMinimum(1)
        self.spinThread.setMaximum(20)
        self.spinThread.setProperty("value", 20)
        self.spinThread.setObjectName("spinThread")
        self.leUserFB = QtWidgets.QLineEdit(Dialog)
        self.leUserFB.setGeometry(QtCore.QRect(30, 580, 171, 20))
        self.leUserFB.setText("")
        self.leUserFB.setObjectName("leUserFB")
        self.pbAddFriead = QtWidgets.QPushButton(Dialog)
        self.pbAddFriead.setGeometry(QtCore.QRect(30, 650, 75, 41))
        self.pbAddFriead.setObjectName("pbAddFriead")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 560, 101, 16))
        self.label_5.setObjectName("label_5")
        self.leAdsList = QtWidgets.QLineEdit(Dialog)
        self.leAdsList.setGeometry(QtCore.QRect(30, 620, 171, 20))
        self.leAdsList.setText("")
        self.leAdsList.setObjectName("leAdsList")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 600, 81, 16))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Venus Tool++"))
        self.twListAcc.headerItem().setText(0, _translate("Dialog", "STT"))
        self.twListAcc.headerItem().setText(1, _translate("Dialog", "UID"))
        self.twListAcc.headerItem().setText(2, _translate("Dialog", "PASS"))
        self.twListAcc.headerItem().setText(3, _translate("Dialog", "2FA"))
        self.twListAcc.headerItem().setText(4, _translate("Dialog", "Pass 2FA"))
        self.twListAcc.headerItem().setText(5, _translate("Dialog", "Cookies"))
        self.twListAcc.headerItem().setText(6, _translate("Dialog", "Token"))
        self.twListAcc.headerItem().setText(7, _translate("Dialog", "Status"))
        self.pbImport.setText(_translate("Dialog", "Nhập Acc"))
        self.label.setText(_translate("Dialog", "Nội dung"))
        self.txtContents.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:19px; background-color:#ffffff;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a31515;\">You traveled within the last 60 days</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Link 415"))
        self.pbSend.setText(_translate("Dialog", "Bắt Đầu"))
        self.label_3.setText(_translate("Dialog", "Luồng chạy"))
        self.label_4.setText(_translate("Dialog", "Delay"))
        self.lePath.setText(_translate("Dialog", "C:\\Users\\trong\\Desktop\\acc.txt"))
        self.pbSelectFile.setText(_translate("Dialog", "..."))
        self.pbAddFriead.setText(_translate("Dialog", "Kết Bạn"))
        self.label_5.setText(_translate("Dialog", "Id user facebook"))
        self.label_6.setText(_translate("Dialog", "Id Ads acount"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
